### ISSUE TITLE
Hummus

### ISSUE THREAD

**Issue by bryanbr23** [bryanbr23/Recipes#174]

**Comment by inspiredtaste** [comment]
Hi, This is Adam with Inspired Taste. So glad that you found our hummus recipe and enjoy it but we don't allow full recipes copied from our site to be used on another public website. I noticed that your recipe category is public. Can you either remove our recipe or change ours to private so you can use it for your own reference?

**Comment by bryanbr23** [comment]
Sure

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
